region: us-east-1

function_name: spotify_archiver
handler: service.handler
description: 
runtime: python3.6

aws_access_key_id: ${AWS_ACCESS_KEY_ID}
aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}

# dist_directory: dist
# timeout: 15
# memory_size: 512

environment_variables:
    spotify_client_id: ${SPOTIFY_CLIENT_ID}
    spotify_client_secret: ${SPOTIFY_CLIENT_SECRET}
    spotify_refresh_token: ${SPOTIFY_REFRESH_TOKEN}

build:
  source_directories: spotify_archiver
